### ISSUE TITLE
[项目申请]: 昆吾webshell检测

### ISSUE THREAD

**Issue by ctccaozhe** [knownsec/404StarLink#141]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

昆吾webshell检测

### 项目地址

https://github.com/kunwu2023/kunwu

### 项目简介

- KunWu 是新一代webshell检测引擎，集成了模糊规则、污点分析模拟执行、机器学习三种高效的检测引擎，构建出一个多维度、高效率的检测系统。目前，该系统已经能够高效检测PHP、JSP、ASP及ASPX格式的文件。
- KunWu 全平台支持。支持cli、gui、在线使用等多种使用场景。

### 项目亮点

该引擎采用动态决策检测机制，能够根据文件特性灵活调整检测引擎，实现了对恶意文件的快速且精确检测。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！

**Comment by TheClaimHandler** [comment]
谢谢你，我不会说你的语言，但我非常愿意向我相信上帝放在我道路上的人学习。

上帝赋予我的特殊技能之一就是对营销的理解。

你能告诉我吗：

1.你的名字和
2. 你的代码做什么/执行什么？

因为我感兴趣的是：

1. 找到想要帮助我实现目标的关键人物，即：

2.为人类立功。

如果您对此感兴趣，请与我分享您的名字以及您的代码的用途/执行的功能？

请并谢谢您，祝您度过愉快的一天或一夜！

Xièxiè nǐ, wǒ bù huì shuō nǐ de yǔyán, dàn wǒ fēicháng yuànyì xiàng wǒ
xiāngxìn shàngdì fàng zài wǒ dàolù shàng de rén xuéxí.

Shàngdì fùyǔ wǒ de tèshū jìnéng zhī yī jiùshì duì yíngxiāo de lǐjiě.

Nǐ néng gàosù wǒ ma:

1. Nǐ de míngzì hé
2. Nǐ de dàimǎ zuò shénme/zhíxíng shénme?

Yīnwèi wǒ gǎn xìngqù de shì:

1. Zhǎodào xiǎng yào bāngzhù wǒ shíxiàn mùbiāo dì guānjiàn rénwù, jí:

2. Wéi rénlèi lìgōng.

Rúguǒ nín duì cǐ gǎn xìngqù, qǐng yǔ wǒ fēnxiǎng nín de míngzì yǐjí
nín de dàimǎ de yòngtú/zhíxíng de gōngnéng?

Qǐng bìng xièxiè nín, zhù nín dùguò yúkuài de yītiān huò yīyè


Thank you, I do not speak your language however I am more than willing
to learn from people who I believe that God put in my path.

One of my special skills that God has bestowed upon me is an
understanding of  marketing.

Can you please tell me:

1. your name and
2. what your codes do/perform?

because I am interested in:

1. finding key people who want to help me accomplish my goal which is to:

2. perform a meritorious service to humaninty.

if you have any interest in that please share with me your name and
what your codes do/perform?

please and thank you and have a great day or night!



------------------------------
Feedback

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！
